# Generated by Django 5.1.7 on 2025-03-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
