# Generated by Django 5.1.7 on 2025-03-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_alter_task_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
