# Generated by Django 5.1.7 on 2025-03-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refresh_token',
            name='token',
            field=models.CharField(unique=True),
        ),
    ]
