# Generated by Django 5.1.7 on 2025-03-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_alter_refresh_token_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='refresh_token',
            name='access',
            field=models.CharField(default='', unique=True),
        ),
    ]
